//
//  Constants.swift
//  AppleStore
//
//  Created by muxammed on 12.10.2022.
//

/// константы
struct Constants {
    static let searchTitle = "Поиск"
    static let searchTextFieldPlaceholder = "Поиск по продуктам и магазинам"
    static let lastViewed = "Недавно просмотренные"
    static let clearText = "Очистить"
    static let queryOptionsText = "Варианты запросов"
    static let productNameOne = "Чехол Incase Flat для MacBook Pro 16 дюймов"
    static let productNameTwo = "Спортивный ремешок Black Unity (для ..."
    static let productNameThree = "Кожанный чехол для MacBook Pro 16 дюймов, золотой"
    static let productNameFour = "iPhone 12 Pro"
    static let productPrice = "3 990.00 руб."
    static let compatibleTextOne = "Совместимо с MacBook Pro - Евгений"
    static let compatibleTextTwo = "MacBook Pro - Евгений"
    static let addToCartText = "Добавить в корзину"
    static let bottomTextOne = "Заказ сегодня в течении дня, доставка:"
    static let bottomTextTwo = "Чт 25 Фев - Бесплатно"
    static let bottomTextThree = "Варианты доставки для местоположения: 115533"
    static let forYouText = "Для вас"
    static let whatsNewText = "Вот что нового"
    static let yourOrderSendedText = "Ваш заказ отправлен"
    static let orderSummaryText = "1 товар, доставка завтра"
    static let inProgressText = "Обрабатывается"
    static let sendedText = "Отправлено"
    static let deliveredText = "Доставлено"
    static let recommendsForYouText = "Рекомендуется вам"
    static let notifyText = "Получайте новости о своем заказе в режиме реального времени."
    static let notifySubText = "Включите уведомления, чтобы получать новости о совем заказе."
    static let yourDevicesText = "Ваши устройства"
    static let showAllText = "Показать все"
    static let largeTitleViewClassName = "_UINavigationBarLargeTitleView"
    static let avatarStringForUDefKey = "avatar"
    static let brownCase2 = "brownCase2"
    static let dz = "dz"
    static let pdf = "pdf"
    static let textFieldBackColor = "textFieldBackColor"
    static let searchTextFieldTintColor = "searchTextFieldTintColor"
    static let productOneUrl = "https://ru-store.ru/catalog/product/chekhol_apple_mqg02zm_a_dark_blue_dlya_macbook_12/page/"
    static let productTwoUrl = "https://ru-store.ru/catalog/watch/"
    static let productThreeUrl = "https://ru-store.ru/catalog/product/chekhol_apple_mqg02zm_a_dark_blue_dlya_macbook_12/page/"
    static let productFourUrl = "https://ru-store.ru/catalog/iphone/"
    static let case2 = "case2"
    static let case3 = "case3"
    static let caseBrown2 = "caseBrown2"
    static let caseBrown3 = "caseBrown3"
    static let AirPods = "AirPods"
    static let AppleCare = "AppleCare"
    static let Beats = "Beats"
    static let compareText = "Сравните модели iPhone"
    static let productOne = "productOne"
    static let productTwo = "productTwo"
    static let productThree = "productThree"
    static let productFour = "productFour"
    static let laptopIconName = "laptopcomputer.and.iphone"
    static let appBadgeIcon = "app.badge"
    static let strelka = "chevron.right"
    static let magnifyingglass = "magnifyingglass"
    static let airpods = "airpods"
    static let tabBarBackColor = "tabBarBackColor"
    static let tabOneTitle = "Купить"
    static let tabTwoTitle = "Для Вас"
    static let personIcon = "person.circle"
    static let tabThreeTitle = "Поиск"
    static let tabFourTitle = "Корзина"
    static let bagIcon = "bag"
    static let trackTintColor = "trackTintColor"
    static let progressTintColor = "progressTintColor"
    static let viewBackground = "viewBackground"
    static let linesColor = "linesColor"
    static let shareIcon = "square.and.arrow.up"
    static let heartIcon = "heart"
    static let checkmarkIcon = "checkmark.circle.fill"
    static let cubeIcon = "cube.box"
    static let strelkaDwa = "chevron.left"
    static let refreshIcon = "arrow.clockwise"
    static let dummySite = "https://re-store.ru"
    static let ownGrayColor = "ownGrayColor"
    static let webViewToolbarColor = "webViewToolbarColor"
    static let checkImageBackColor = "checkImageBackColor"
    static let addToCartButtonColor = "addToCartButtonColor"
    static let circleTwoColor = "circleTwoColor"
    static let gradOne = "gradOne"
    static let gradTwo = "gradTwo"
    static let gradTri = "gradTri"
    static let navBackColor = "navBackColor"
    static let searchIconTint = "searchIconTint"
}
